
project_id = "ggclvurfcykbwmhfftkn"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[[storage.buckets]]
name = "merchant_images"
public = true

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "https://11abe201-5c2e-4bfd-8399-358f356fd184.lovableproject.com"
]
jwt_expiry = 86400 # 24 hours, so the access token lasts a day
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false
refresh_token_expiry = 31536000 # 1 year
