
project_id = "ggclvurfcykbwmhfftkn"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[[storage.buckets]]
name = "merchant_images"
public = true

[auth]
site_url = "https://app.booqit.in"
additional_redirect_urls = [
  "http://localhost:3000",
  "https://localhost:3000",
  "https://11abe201-5c2e-4bfd-8399-358f356fd184.lovableproject.com",
  "https://app.booqit.in/verify",
  "http://localhost:3000/verify",
  "https://localhost:3000/verify",
  "https://11abe201-5c2e-4bfd-8399-358f356fd184.lovableproject.com/verify",
  "https://app.booqit.in/reset-password",
  "http://localhost:3000/reset-password",
  "https://localhost:3000/reset-password",
  "https://11abe201-5c2e-4bfd-8399-358f356fd184.lovableproject.com/reset-password"
]
jwt_expiry = 86400 # 24 hours
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = true
# Set password reset token expiry to 1 hour (3600 seconds)
password_reset_expiry = 3600
# Ensure email delivery is reliable
enable_anonymous_sign_ins = false
disable_signup = false
# Email rate limiting - reasonable limits for production use
email_rate_limit = 10
email_rate_limit_window = 3600 # 1 hour window
